language: php

os:
  - linux
  - windows

php:
  - 5.3.29
  - 5.4.45
  - 5.5.29
  - 5.6.13

before_script:
  - composer self-update
  - composer install
  - pyrus install pear/PHP_CodeSniffer
  - phpenv rehash

script:
  - phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
