
paginate: 1 
permalink: none
paginate_path: "page:num"
exclude: ["README.md"] 
highlighter: pygments
markdown: kramdown
kramdown:
    input: GFM

defaults:
  -
    scope:
      path: "" 
    values:
      title: PHP PhantomJS

title: PHP PhantomJs
description: Run PhantomJS scripts through PHP

author:
  name: Jonny W

github:
  username: jonnnnyw
  repo: php-phantomjs
  watch: true
  fork: true

rss_path: feed.xml

BASE_PATH: http://jonnnnyw.github.io/php-phantomjs
